name: Python Web App CI/CD

on:
  push:
    branches:
      - main
      - feature/**   # This will trigger on feature branches as well
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Add your tests here (if any), for simplicity, we are skipping it
          echo "No tests defined yet"

      - name: Deploy to Heroku
        run: |
          echo "Deploying to Heroku or another cloud service"
          # Example: heroku login & heroku deploy steps
          # For now, just print deployment command
